repoURL: https://github.com/helm/charts
path: stable/nginx-ingress
namespace: ingress-nginx-vpc-link
values:
  controller:
    image:
      repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: "0.28.0"

    electionID: ingress-controller-leader-vpc-link
    ingressClass: nginx-vpc-link

    publishService:
      enabled: true

    replicaCount: 2

    resources:
      limits:
        cpu: 300m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
      omitclusterIP: true

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  defaultBackend:
    enabled: false
