repoURL: https://github.com/helm/charts
path: stable/prometheus-blackbox-exporter
namespace: monitoring
values:
  resources:
    limits:
      memory: 100Mi
    requests:
      memory: 16Mi

  config:
    modules:
      http_2xx:
        http:
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
        prober: http
        timeout: 10s
      tcp:
        prober: tcp
        timeout: 10s
        tcp: {}